version: '3'

services:
  web:
    image: azamuku-test
    env_file:
        - variables.test.env
    ports:
      - "5000:5000"
    command: python run.py
    volumes:
      - ./azamuku:/code
#    restart: "unless-stopped"
  mongo:
    image: mongo:3.4.10
    env_file:
        - variables.test.env
    volumes:
      - ./volumes/mongo/db:/data/db
    ports:
      - 27017:27017
    restart: "unless-stopped"
  redis:
    image: redis:4.0.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/var/lib/redis
    restart: "unless-stopped"

